[package]
name = "ibus-dl"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = ["wrappers"]
wrappers = ["glib"]

[dependencies]
dlib = "0.5"
once_cell = "1.9"
glib = { version = "0.14", optional = true }
